name: Build

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      canUseSauce: ${{ steps.check_sauce_access.outputs.result == 'true' }}
      tag: ${{ steps.extract_tag.outputs.result }}
      isMainBranch: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: check sauce access
        id: check_sauce_access
        run: |
          if ! [[ -z "$SAUCE_USERNAME" ]] && ! [[ -z "$SAUCE_ACCESS_KEY" ]]; then
            echo "::set-output name=result::true"
          fi
        env:
          CI: true
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      - name: extract tag
        id: extract_tag
        uses: actions/github-script@v3
        with:
          script: |
            const prefix = 'refs/tags/';
            const ref = context.ref;
            return ref.startsWith(prefix) ? ref.substring(prefix.length) : '';
          result-encoding: string

  build:
    needs: config
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check package-lock.json version
        id: extract_tag
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            if (
              JSON.parse(fs.readFileSync('./package-lock.json', { encoding: 'utf8' }))
                .lockfileVersion !== 2
            ) {
              throw new Error(
                'Expecting package-lock.json version to be 2. Please make sure you are using npm 7.'
              );
            }

      - name: cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: install
        run: |
          npm ci
        env:
          CI: true

      - name: lint
        run: |
          npm run lint
          npm run prettier:verify

      - name: set version
        run: |
          node ./scripts/set-package-version.js
        env:
          CI: true
          TAG: ${{ needs.config.outputs.tag }}

      - name: build
        run: |
          npm run build:ci
          npm run docs
          # check that hls.js doesn't error if requiring in node
          # see https://github.com/video-dev/hls.js/pull/1642
          node -e 'require("./" + require("./package.json").main)'
        env:
          CI: true

      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            **
            !**/[.]*/**
            !**/node_modules/

  release_npm:
    needs: [config, build]
    # if: needs.config.outputs.tag || needs.config.outputs.isMainBranch == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: download build
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: install
        run: |
          npm ci
        env:
          CI: true

      - name: publish to npm
        run: |
          ./scripts/publish-npm.sh
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG: ${{ needs.config.outputs.tag }}
